"""
app/agent/planning.py
---------------------
Planning pipeline for the PLANNING stage.

Sub-stages:
  1. Codebase Survey - agentic loop (read-only tools, max N turns)
  2. Best-of-N Design Generation - N parallel structured LLM calls
  3. Design Review Panel - 3 parallel LLM reviewers
  4. Pitfall Detection - deterministic + 1 LLM call
  5. Plan Consolidation - 1 LLM call to merge winner + pitfall mitigations

Output: PlanningResult stored in planning_results table.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from dataclasses import asdict, dataclass, field
from typing import Any

from app.agent.config import (
    PLANNING_BEST_OF_N,
    PLANNING_JUDGE_MAX_TOKENS,
    PLANNING_MAX_DESIGN_RETRIES,
    PLANNING_SURVEY_MAX_TURNS,
    PLANNING_MAX_FILES,
    PLANNING_MAX_STEPS,
    PROJECT_ROOT,
    check_context_saturation,
)
from app.agent.llm_client import call_llm, is_shutting_down, ShutdownError
from app.agent.verdicts import Vote, Verdict, tally_votes

logger = logging.getLogger(__name__)
AGENT_NAME = "Planning Pipeline"

# ---------------------------------------------------------------------------
# Design personas — each proposal in the Best-of-N pool is generated by a
# different architect persona with a distinct primary concern.  The same task
# description and codebase survey are sent to every persona; variance comes
# from the framing, not from sampling hyperparameters.
#
# If PLANNING_BEST_OF_N > len(_DESIGN_PERSONAS), personas repeat round-robin.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Reviewer relevance — unit-test tasks only need a subset of the review panel.
# Performance and security reviewers have no signal to give on "write N pytest
# assertions for a dataclass"; running them wastes LLM slots and produces
# NOT_SUITABLE verdicts (now treated as abstentions) or false REJECTED signals.
# ---------------------------------------------------------------------------

_UNIT_TEST_REVIEWER_SUBSET = frozenset({
    "coupling_reviewer",
    "interface_reviewer",
    "testability_reviewer",
})

_UNIT_TEST_TITLE_PATTERNS = ("test_", "test ", "tests for", "testcare", "testplant", "testcreate", "testupdate", "testdelete")
_UNIT_TEST_DESC_PATTERNS = ("@pytest", "def test_", "pytest.fixture", "assert ", "dataclass", " enum ", "unit test")


def _is_unit_test_task(title: str, description: str) -> bool:
    """Return True when heuristics indicate a pure unit-test writing task."""
    title_l = title.lower()
    if any(title_l.startswith(p) or p in title_l for p in _UNIT_TEST_TITLE_PATTERNS):
        return True
    desc_l = (description or "").lower()
    return any(p in desc_l for p in _UNIT_TEST_DESC_PATTERNS)


# ---------------------------------------------------------------------------
# Complexity classification — simple tasks get a lite reviewer panel and a
# smaller design pool (2 proposals instead of 5).  This avoids the full
# gauntlet for trivially-scoped greenfield scripts.
# ---------------------------------------------------------------------------

_SIMPLE_TASK_REVIEWER_SUBSET = frozenset({
    "coupling_reviewer",
    "testability_reviewer",
})

_SIMPLE_KEYWORDS = (
    "greenfield", "simple", "naive", "single file", "single function",
    "one function", "write a function", "add a function", "basic",
    "minimal", "straightforward", "write a script", "small utility",
)


def _is_simple_task(title: str, description: str, survey: str = "") -> bool:
    """Return True when heuristics indicate a low-complexity task.

    Simple tasks skip the security/performance reviewers (they have nothing
    to say about a 30-line function) and generate only 2 design proposals
    instead of the full PLANNING_BEST_OF_N pool.
    """
    combined = (title + " " + (description or "")).lower()
    if any(kw in combined for kw in _SIMPLE_KEYWORDS):
        return True
    # Short description almost always means narrow scope
    if len(description or "") < 150:
        return True
    # Survey explicitly says empty/greenfield project
    survey_l = (survey or "").lower()
    if "greenfield" in survey_l or ("empty" in survey_l and "project" in survey_l):
        return True
    return False


def _extract_spec_constraints(description: str) -> str:
    """Extract explicit algorithmic/design constraints from a task description.

    Returns a bulleted list of constraints to inject into the design prompt,
    or an empty string if none are detected.
    """
    if not description:
        return ""

    desc_lower = description.lower()
    constraints: list[str] = []

    constraint_signals = [
        ("naive recursive", "Algorithm must be naive recursive — no memoization, no iteration"),
        ("naive recursion", "Algorithm must be naive recursive — no memoization, no iteration"),
        ("no memoization", "Memoization is explicitly forbidden"),
        ("without memoization", "Memoization is explicitly forbidden"),
        ("no caching", "Caching is explicitly forbidden"),
        ("without caching", "Caching is explicitly forbidden"),
        ("simple recursive", "Algorithm must be simple/naive recursive"),
        ("do not use", "Explicit exclusion present — see description"),
        ("must not use", "Explicit exclusion present — see description"),
        ("intentionally not", "Intentional design constraint present — see description"),
        ("explicitly", "Explicit constraint present — see description"),
        ("keep it simple", "Implementation must remain simple — no unnecessary abstractions"),
        ("greenfield", "This is a greenfield project — start from scratch, minimal structure only"),
    ]

    for signal, label in constraint_signals:
        if signal in desc_lower:
            constraints.append(f"• {label}")

    if not constraints:
        return ""

    return (
        "The task description contains BINDING design constraints:\n"
        + "\n".join(constraints)
        + "\n\nYou MUST respect these constraints. Do not 'improve' the design beyond what is asked."
    )


def _scan_existing_files(project_root: str, survey_text: str) -> list[str]:
    """Return a list of existing source files in the project root (up to 30).

    Used to warn the design LLM that the project is not greenfield.
    Skips hidden dirs, venv, __pycache__, node_modules.
    """
    import os

    _SKIP_DIRS = frozenset({
        "venv", ".venv", "env", "__pycache__", "node_modules", ".git",
        ".archive", ".maestro-worktrees", "dist", "build", ".eggs",
        "site-packages", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    })
    found: list[str] = []

    try:
        for root, dirs, files in os.walk(project_root):
            dirs[:] = [
                d for d in dirs
                if d not in _SKIP_DIRS and not d.startswith(".")
            ]
            rel_root = os.path.relpath(root, project_root)
            for fname in files:
                if fname.startswith("."):
                    continue
                rel = os.path.join(rel_root, fname).replace("\\", "/")
                if rel.startswith("./"):
                    rel = rel[2:]
                found.append(rel)
                if len(found) >= 30:
                    return found
    except Exception:
        pass

    return found


_DESIGN_PERSONAS: list[tuple[str, str]] = [
    (
        "Correctness & Testability",
        "Your primary concern is correctness and testability. "
        "Design for explicit, predictable error handling and well-defined failure modes. "
        "Create clean test seams — each component must be independently verifiable without "
        "needing to wire up the whole system. Prefer explicit over implicit. "
        "In your design_rationale, explain how the structure makes the system easy to test "
        "and how errors propagate clearly.",
    ),
    (
        "Security & Defensive Robustness",
        "Your primary concern is security and defensive design. "
        "Minimise the attack surface. Validate all inputs at every trust boundary. "
        "Use safe defaults and fail closed on unexpected conditions. "
        "Avoid over-privileged components — each module should access only what it needs. "
        "Think through what can go wrong and design around it. "
        "In your design_rationale, explain the key trust boundaries, what is validated where, "
        "and how the design degrades safely under adversarial or unexpected input.",
    ),
    (
        "Code Clarity & Codebase Consistency",
        "Your primary concern is code clarity and consistency with the existing codebase. "
        "Study the survey carefully: match the naming conventions, file layout, module "
        "structure, and idioms already present. A contributor familiar with the existing code "
        "should be able to predict every design choice you make before reading it. "
        "Prefer conventional structure over clever structure. Avoid introducing new patterns "
        "when existing ones already solve the problem. "
        "In your design_rationale, describe specifically how your design mirrors the patterns "
        "you observed in the codebase survey.",
    ),
    (
        "Performance & Operational Efficiency",
        "Your primary concern is performance and resource efficiency. "
        "Minimise unnecessary computation, I/O, and database round-trips on the critical path. "
        "Consider caching strategies and async opportunities that reduce latency where it matters. "
        "Avoid premature abstraction that adds indirection without benefit. "
        "Design data flows so that the common case is fast; handle the slow path explicitly. "
        "In your design_rationale, identify the performance-critical paths and explain the "
        "specific choices that keep them efficient.",
    ),
    (
        "Clean Architecture & Boundary Clarity",
        "Your primary concern is clean architecture and strict separation of concerns. "
        "Each module must have one clear, narrow responsibility. Define explicit interface "
        "contracts between components — what each provides, what it consumes, what invariants "
        "it upholds. Minimise coupling: a change in one area should not ripple unexpectedly. "
        "Design the system so its structure is self-evident from the file layout alone. "
        "In your design_rationale, explain exactly where you drew each boundary and why each "
        "component owns the responsibilities it does.",
    ),
]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class FileManifestEntry:
    path: str
    action: str  # create | modify | delete
    purpose: str
    estimated_lines: int = 0
    depends_on: list[str] = field(default_factory=list)


@dataclass(slots=True)
class InterfaceContract:
    component: str
    provides: list[str] = field(default_factory=list)
    consumes: list[str] = field(default_factory=list)
    invariants: list[str] = field(default_factory=list)


@dataclass(slots=True)
class TestStrategyEntry:
    component: str
    test_file: str
    test_cases: list[str] = field(default_factory=list)
    fixtures: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ImplementationStep:
    order: int
    component: str
    files: list[str] = field(default_factory=list)
    description: str = ""
    depends_on: list[str] = field(default_factory=list)
    estimated_context_tokens: int = 0


@dataclass(slots=True)
class PlanningResult:
    task_id: str
    design_rationale: str = ""
    file_manifest: list[FileManifestEntry] = field(default_factory=list)
    dependency_graph: dict[str, list[str]] = field(default_factory=dict)
    interface_contracts: list[InterfaceContract] = field(default_factory=list)
    test_strategy: list[TestStrategyEntry] = field(default_factory=list)
    implementation_steps: list[ImplementationStep] = field(default_factory=list)
    pitfalls_identified: list[dict] = field(default_factory=list)
    review_votes: list[Vote] = field(default_factory=list)
    best_of_n_designs: list[dict] = field(default_factory=list)
    selected_design_index: int = 0
    confidence: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    scope_verdict: str = ""      # non-empty when design scope is too large
    survey_summary: str = ""     # codebase survey result, passed to subdivision


# ---------------------------------------------------------------------------
# Read-only tools for codebase survey
# ---------------------------------------------------------------------------

SURVEY_TOOLS = [
    "read_file", "count_lines",
    "search_files", "find_files", "list_directory",
    "git_log", "git_blame",
    "get_task", "list_tasks",
    "submit_work",
]


def _get_survey_tool_schemas() -> list[dict]:
    """Return OpenAI-format tool schemas for the survey agent."""
    from app.agent.tools import TOOL_SCHEMAS
    return [s for s in TOOL_SCHEMAS if s["function"]["name"] in SURVEY_TOOLS]


# ---------------------------------------------------------------------------
# Pipeline class
# ---------------------------------------------------------------------------

class PlanningPipeline:
    """Orchestrates the planning pipeline for a single task."""

    def __init__(
        self,
        task_id: str,
        task_title: str,
        task_description: str,
        all_tasks: list[dict],
        *,
        llm_base_url: str | None = None,
        llm_model: str | None = None,
        llm_id: int | None = None,
        budget_id: int | None = None,
        max_context: int | None = None,
        run_row_id: int | None = None,
        project_name: str | None = None,
        project_root: str | None = None,
    ):
        self.task_id = task_id
        self.task_title = task_title
        self.task_description = task_description
        self.all_tasks = all_tasks
        self.llm_base_url = llm_base_url
        self.llm_model = llm_model
        self.llm_id = llm_id
        self.budget_id = budget_id
        self.max_context = max_context
        self.run_row_id = run_row_id
        self.project_name = project_name
        self.project_root = project_root
        self._total_prompt = 0
        self._total_completion = 0
        # Set in run() after the survey, used by _stage_design_review
        self._is_simple: bool = False
        self._effective_best_of_n: int = PLANNING_BEST_OF_N
        # Lazily computed architecture context (cached on first access)
        self.__arch_ctx: str | None = None

    @property
    def _arch_ctx(self) -> str:
        if self.__arch_ctx is None:
            if not self.project_name:
                self.__arch_ctx = ""
            else:
                try:
                    from app.agent.project_snapshot import build_architecture_context
                    self.__arch_ctx = build_architecture_context(
                        self.project_name, agent_type="planning"
                    ) or ""
                except Exception:
                    self.__arch_ctx = ""
        return self.__arch_ctx

    async def run(self) -> PlanningResult:
        """Execute all planning sub-stages and return the result."""
        from app.agent.llm_client import set_llm_session_context
        set_llm_session_context(AGENT_NAME)
        logger.info(f"[{AGENT_NAME}] Starting pipeline for task '%s'", self.task_id)

        # Stage 1: Codebase survey
        survey_summary = await self._stage_codebase_survey()

        # Classify complexity after the survey so we can factor in the survey result.
        # Unit-test tasks are already handled by their own reviewer subset; simple tasks
        # get a reduced design pool (2 proposals) and a lighter reviewer panel.
        self._is_simple = (
            not _is_unit_test_task(self.task_title, self.task_description)
            and _is_simple_task(self.task_title, self.task_description, survey_summary)
        )
        self._effective_best_of_n = 2 if self._is_simple else PLANNING_BEST_OF_N
        if self._is_simple:
            logger.info(
                "[%s] Simple task detected — reducing design pool to %d and using lite reviewer panel.",
                AGENT_NAME, self._effective_best_of_n,
            )

        # Inject demotion history so designers know why prior INDEV attempts failed.
        # This supplements the failure notes already appended to task.description.
        try:
            from app.database import get_task as _get_task_for_history
            _task_hist = _get_task_for_history(self.task_id)
            if _task_hist and _task_hist.demotion_history:
                _recent = _task_hist.demotion_history[-3:]
                _hist_block = "\n\n[PRIOR INDEV FAILURES — consider before designing]\n"
                for _d in _recent:
                    _ts = _d.get("timestamp", "?")[:19]
                    _reason = _d.get("reason", "?")
                    _hist_block += f"  {_ts}: {_reason[:400]}\n"
                survey_summary += _hist_block
        except Exception:
            pass

        # Retry loop for stages 2-3
        best_designs: list[dict] = []
        selected_index = 0
        review_votes: list[Vote] = []
        winning_design: dict = {}
        scope_verdict = ""
        _pipeline_passed = False  # set to True when a review tally passes

        for attempt in range(PLANNING_MAX_DESIGN_RETRIES):
            if is_shutting_down():
                raise ShutdownError("Server is shutting down")

            # Stage 2: Best-of-N design generation
            designs = await self._stage_design_generation(survey_summary, self._effective_best_of_n)
            best_designs = designs

            # Warn when only some parallel design calls succeeded — the judge is
            # picking from a degraded pool; surface this so the user can see why
            # the plan might be weaker than expected.
            valid_count = sum(1 for d in designs if "error" not in d and "parse_error" not in d)
            if 0 < valid_count < self._effective_best_of_n:
                _partial_warn = (
                    f"[PARTIAL GENERATION on attempt {attempt + 1}]: "
                    f"Only {valid_count}/{self._effective_best_of_n} design proposals succeeded. "
                    "Selected design may not represent the best available option."
                )
                logger.warning("[%s] %s", AGENT_NAME, _partial_warn)
                survey_summary += f"\n\n{_partial_warn}"

            # Judge selects winner
            selected_index, winning_design = await self._stage_judge_designs(
                designs, survey_summary
            )

            # Short-circuit: if every design generation call failed the judge returns a
            # failed_generation dummy.  Running the reviewer panel on it wastes 5 LLM
            # calls that will all REJECT for the same trivial reason.  Skip straight to
            # the next retry attempt instead.
            if winning_design.get("failed_generation"):
                logger.warning(
                    f"[{AGENT_NAME}] All designs failed on attempt %d/%d — "
                    "skipping reviewer panel and retrying design generation.",
                    attempt + 1, PLANNING_MAX_DESIGN_RETRIES,
                )
                if attempt < PLANNING_MAX_DESIGN_RETRIES - 1:
                    survey_summary += (
                        f"\n\n[DESIGN GENERATION FAILED on attempt {attempt+1}]: "
                        "All parallel design calls timed out or errored. "
                        "Try simpler designs with fewer files."
                    )
                # Force tally to rejected so the outer else-branch fires on the last attempt
                review_votes = [Vote(
                    stage="design_generation",
                    verdict=Verdict.REJECTED,
                    confidence=5,
                    justification="All design generation calls failed (timeout/error). No design to review.",
                )]
                continue

            # Scope guard: if design is too broad, signal subdivision immediately
            scope_reason = self._check_scope(winning_design)
            if scope_reason:
                logger.info(
                    f"[{AGENT_NAME}] Scope too large on attempt %d — %s",
                    attempt + 1, scope_reason,
                )
                review_votes = [Vote(
                    stage="scope_checker",
                    verdict=Verdict.SUBDIVIDE_IDEA,
                    confidence=95,
                    justification=scope_reason,
                )]
                tally_votes(review_votes)  # noqa: F841 — called for side-effect logging
                scope_verdict = scope_reason
                _pipeline_passed = True  # scope triggers subdivision, not a failure
                break  # No retry — redesigning won't shrink the task

            # Stage 3: Design review panel
            votes = await self._stage_design_review(winning_design, survey_summary)
            review_votes = votes

            tally = tally_votes(votes)
            if tally.outcome in ("passed", "conditional_pass", "warned", "subdivide"):
                logger.info(f"[{AGENT_NAME}] Design review finished on attempt %d: %s", attempt + 1, tally.outcome)
                _pipeline_passed = True
                break
            elif tally.outcome == "needs_research":
                logger.info(
                    f"[{AGENT_NAME}] Design review needs research (attempt %d/%d): %s",
                    attempt + 1, PLANNING_MAX_DESIGN_RETRIES, tally.summary,
                )
                # Trigger research agent inline to resolve the unknowns
                from app.agent.research import run_research
                research_question = f"Investigate design review unknowns: {tally.summary}"
                research_context = {
                    "task_title": self.task_title,
                    "task_description": self.task_description,
                    "design_rationale": winning_design.get("design_rationale", ""),
                    "rejection_reasons": tally.rejection_reasons,
                }
                try:
                    research_result = await run_research(
                        question=research_question,
                        context=research_context,
                        task_id=self.task_id,
                        llm_id=self.llm_id,
                        budget_id=self.budget_id,
                        llm_base_url=self.llm_base_url,
                        llm_model=self.llm_model,
                    )
                    # Feed findings back into survey_summary for the next attempt
                    survey_summary += f"\n\n[RESEARCH FINDINGS from attempt {attempt+1}]:\n{research_result.findings}"
                    self._total_prompt += research_result.prompt_tokens
                    self._total_completion += research_result.completion_tokens
                except Exception as exc:
                    logger.error(f"[{AGENT_NAME}] Inline research failed: %s", exc)
                    survey_summary += f"\n\n[RESEARCH FAILED from attempt {attempt+1}]: {exc}"
            else:
                logger.info(
                    f"[{AGENT_NAME}] Design rejected (attempt %d/%d): %s",
                    attempt + 1, PLANNING_MAX_DESIGN_RETRIES, tally.summary,
                )
                if attempt < PLANNING_MAX_DESIGN_RETRIES - 1:
                    # Feed rejection reasons back into next iteration via survey
                    rejection_feedback = "; ".join(tally.rejection_reasons)
                    survey_summary += f"\n\n[REVIEWER FEEDBACK from attempt {attempt+1}]: {rejection_feedback}"

        if scope_verdict:
            # Skip stages 4-5 — no point polishing a design that will be split
            pitfalls: list[dict] = []
            consolidated = winning_design
        elif not _pipeline_passed:
            # All design attempts were rejected — don't waste LLM calls on pitfall
            # detection and consolidation for a design the reviewers already rejected.
            logger.warning(
                "[%s] All %d design attempts rejected — skipping stages 4-5, returning failure.",
                AGENT_NAME, PLANNING_MAX_DESIGN_RETRIES,
            )
            pitfalls = []
            consolidated = winning_design or {}
        else:
            # Stage 4: Pitfall detection
            pitfalls = await self._stage_pitfall_detection(winning_design, survey_summary)

            # Stage 5: Plan consolidation
            consolidated = await self._stage_consolidation(
                winning_design, pitfalls, survey_summary
            )

        # Build result
        result = self._build_result(
            consolidated, best_designs, selected_index,
            review_votes, pitfalls, survey_summary,
            passed=_pipeline_passed,
        )
        result.scope_verdict = scope_verdict
        result.survey_summary = survey_summary

        # Persist to database
        self._store_result(result)

        return result

    # ------------------------------------------------------------------
    # Stage 1: Codebase Survey
    # ------------------------------------------------------------------

    async def _stage_codebase_survey(self) -> str:
        """Run an agentic loop with read-only tools to survey the codebase."""
        from app.agent.tools import dispatch_tool, _restrict_reads_to_root as _survey_root_flag

        _arch = self._arch_ctx
        system_prompt = (
            "You are a codebase surveyor. Your job is to understand the existing code "
            "structure relevant to the following task.\n\n"
            "WORKFLOW:\n"
            "1. Use tools to read 3-8 key files most relevant to the task.\n"
            "2. Once you have a clear picture of the existing structure, STOP reading "
            "and synthesize your findings.\n"
            "3. Output a single message starting with 'SURVEY_COMPLETE:' followed by "
            "your summary. Do NOT keep reading once you understand the key structure.\n\n"
            "SYNTHESIS TRIGGERS — emit SURVEY_COMPLETE when ANY of these are true:\n"
            "- You have read 5+ files and understand the relevant interfaces.\n"
            "- You have confirmed the relevant modules and their responsibilities.\n"
            "- You have identified what needs to change and what can be reused.\n\n"
            f"Task: {self.task_title}\n"
            f"Description: {self.task_description}"
            + (f"\n\n{_arch}" if _arch else "")
        )

        messages: list[dict] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": (
                "Survey the codebase. Focus only on files most relevant to this task. "
                "Read 3-8 key files, then immediately emit SURVEY_COMPLETE: with your summary. "
                "Do not exhaustively read every file — stop once you understand the key structure."
            )},
        ]

        tool_schemas = _get_survey_tool_schemas()
        survey_result = ""
        content = ""
        _ctx_warned: set[float] = set()
        _turn_warned: set[int] = set()

        # Repetition guard: track (tool_name, arguments_hash)
        _tool_call_history: set[tuple[str, str]] = set()

        # RC5: Restrict absolute-path reads to this project's root for the survey phase.
        # Prevents the LLM from wandering into unrelated project trees on the same machine.
        _root_token = _survey_root_flag.set(True)
        try:
            for turn in range(PLANNING_SURVEY_MAX_TURNS):
                if is_shutting_down():
                    raise ShutdownError("Server is shutting down")

                # Context saturation check
                if check_context_saturation(
                    response.get("usage", {}).get("prompt_tokens", 0) if turn > 0 else 0,
                    self.max_context or 0,
                    _ctx_warned,
                    messages,
                ):
                    logger.warning("Planning survey context saturation (turn %d) - terminating", turn)
                    break

                # Turn saturation check
                from app.agent.config import check_turn_saturation
                if check_turn_saturation(
                    turn, PLANNING_SURVEY_MAX_TURNS, _turn_warned, messages
                ):
                    pass

                response = await call_llm(
                    messages,
                    base_url=self.llm_base_url,
                    model=self.llm_model,
                    tools=tool_schemas,
                    task_id=self.task_id,
                    llm_id=self.llm_id,
                    budget_id=self.budget_id,
                    agent_name=AGENT_NAME,
                )

                self._track_tokens(response)

                # Context saturation check
                if check_context_saturation(
                    response.get("usage", {}).get("prompt_tokens", 0),
                    self.max_context or 0,
                    _ctx_warned,
                    messages,
                ):
                    logger.warning(f"[{AGENT_NAME}] Survey context saturation (turn %d) - terminating", turn + 1)
                    break
                choice = response.get("choices", [{}])[0]
                msg = choice.get("message", {})
                content = msg.get("content", "")
                tool_calls = msg.get("tool_calls", [])

                messages.append(msg)

                # Check for completion signal
                if content and "SURVEY_COMPLETE:" in content:
                    survey_result = content.split("SURVEY_COMPLETE:", 1)[1].strip()
                    logger.info(f"[{AGENT_NAME}] Survey completed at turn %d/%d",
                                turn + 1, PLANNING_SURVEY_MAX_TURNS)
                    break

                # Dispatch tool calls
                if tool_calls:
                    for tc in tool_calls:
                        fn_name = tc["function"]["name"]
                        fn_args_raw = tc["function"]["arguments"]

                        # Guard: Check for repeated tool calls with same args
                        args_str = json.dumps(fn_args_raw, sort_keys=True)
                        call_key = (fn_name, args_str)
                        if call_key in _tool_call_history:
                            logger.warning(
                                f"[{AGENT_NAME}] Repetitive tool call detected: %s(%s). Breaking survey loop.",
                                fn_name, args_str
                            )
                            survey_result = content or "Survey terminated due to tool call loop."
                            break
                        _tool_call_history.add(call_key)

                        fn_args = fn_args_raw if isinstance(fn_args_raw, dict) else json.loads(fn_args_raw)
                        try:
                            result = dispatch_tool(fn_name, fn_args)
                        except Exception as e:
                            result = f"Error: {e}"
                        result_str = str(result)[:4000]
                        logger.debug(f"[{AGENT_NAME}] Survey turn %d: %s(%s) → %d chars",
                                     turn + 1, fn_name,
                                     ", ".join(f"{k}={v!r}" for k, v in fn_args.items()),
                                     len(result_str))
                        messages.append({
                            "role": "tool",
                            "tool_call_id": tc["id"],
                            "content": result_str,
                        })

                        # Detect submit_work
                        if fn_name == "submit_work":
                            try:
                                terminal_data = json.loads(result_str)
                                if terminal_data.get("__maestro_terminal__") is True:
                                    logger.info(f"[{AGENT_NAME}] Survey submit_work detected - signal=%s", terminal_data.get("signal"))
                                    survey_result = terminal_data.get("summary", content)
                                    break # Inner tool loop
                            except (json.JSONDecodeError, ValueError):
                                pass

                        if survey_result:
                            break  # Outer turn loop
                        continue
                    if survey_result: # Loop broken by guard
                        break
                elif not content:
                    break
        finally:
            _survey_root_flag.reset(_root_token)

        if not survey_result:
            logger.warning(
                f"[{AGENT_NAME}] Survey exhausted %d turns without SURVEY_COMPLETE signal. "
                "Using last LLM response (%d chars) as fallback — design quality may be reduced.",
                PLANNING_SURVEY_MAX_TURNS, len(content),
            )
            survey_result = content or "Survey completed without explicit summary."

        logger.info(f"[{AGENT_NAME}] Codebase survey completed (%d chars)", len(survey_result))
        return survey_result

    # ------------------------------------------------------------------
    # Stage 2: Best-of-N Design Generation
    # ------------------------------------------------------------------

    async def _stage_design_generation(self, survey: str, best_of_n: int | None = None) -> list[dict]:
        """Generate N design proposals in parallel using submit_work tool."""
        n = best_of_n if best_of_n is not None else PLANNING_BEST_OF_N
        _arch = self._arch_ctx
        
        from app.agent.tools import TOOL_SCHEMAS
        submit_work_schema = [s for s in TOOL_SCHEMAS if s["function"]["name"] == "submit_work"]

        _instruction = (
            "Based on the codebase survey and task description, produce a detailed "
            "implementation design by calling the `submit_work` tool.\n\n"
            "Use signal='DESIGN_COMPLETE' and provide the following in the tool arguments:\n"
            "- design_rationale: string explaining the approach\n"
            "- file_manifest: list of {path, action, purpose, estimated_lines, depends_on}\n"
            "- dependency_graph: dict mapping component -> [dependencies]\n"
            "- interface_contracts: list of {component, provides, consumes, invariants}\n"
            "- test_strategy: list of {component, test_file, test_cases, fixtures}\n"
            "- implementation_steps: list of {order, component, files, description, depends_on, estimated_context_tokens}\n"
        )

        # Warn the design LLM when existing files are present on disk
        _existing_files = _scan_existing_files(self.project_root, survey) if self.project_root else []
        _greenfield_warning = ""
        if _existing_files:
            _greenfield_warning = (
                "\n\n⚠ NON-GREENFIELD WARNING:\n"
                "The following files already exist on disk. Do NOT propose creating them again "
                "unless the task explicitly requires replacing them. If the existing implementation "
                "already satisfies the task, set signal='ACCEPTED' and all file_manifest "
                "actions to 'verify'.\n"
                "Existing files:\n"
                + "\n".join(f"  - {p}" for p in _existing_files[:20])
            )

        _spec_block = _extract_spec_constraints(self.task_description)

        user_msg = (
            f"Task: {self.task_title}\n"
            f"Description: {self.task_description}\n\n"
            f"Codebase Survey:\n{survey[:8000]}"
            + _greenfield_warning
        )

        tasks = []
        for i in range(n):
            persona_label, persona_concern = _DESIGN_PERSONAS[i % len(_DESIGN_PERSONAS)]
            _spec_suffix = (
                "\n\n*** SPEC COMPLIANCE — BINDING CONSTRAINTS ***\n"
                + _spec_block
                + "\n*** END SPEC COMPLIANCE ***"
            ) if _spec_block else ""
            system_prompt = (
                f"You are a software architect. Primary concern: {persona_label}.\n"
                f"{persona_concern}"
                + _spec_suffix
                + "\n\n"
                + _instruction
                + (f"\n\n{_arch}" if _arch else "")
            )
            tasks.append(call_llm(
                [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_msg},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                tools=submit_work_schema,
                tool_choice={"type": "function", "function": {"name": "submit_work"}},
                total_timeout_secs=600,
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=f"{AGENT_NAME}[{persona_label}]",
            ))

        if is_shutting_down():
            raise ShutdownError("Server is shutting down")

        responses = await asyncio.gather(*tasks, return_exceptions=True)

        designs = []
        for i, resp in enumerate(responses):
            if isinstance(resp, Exception):
                if isinstance(resp, ShutdownError):
                    raise resp
                logger.warning(f"[{AGENT_NAME}] Design %d failed: %s", i, resp)
                designs.append({"error": str(resp)})
                continue
            
            self._track_tokens(resp)
            msg = resp.get("choices", [{}])[0].get("message", {})
            tool_calls = msg.get("tool_calls", [])
            
            design = {}
            if tool_calls:
                tc = tool_calls[0]
                try:
                    args = tc.get("function", {}).get("arguments", "{}")
                    design = json.loads(args) if isinstance(args, str) else args
                except (json.JSONDecodeError, ValueError):
                    design = {"raw": str(msg), "parse_error": True}
            else:
                content = msg.get("content", "")
                try:
                    design, _ = json.JSONDecoder().raw_decode(content.lstrip())
                except (json.JSONDecodeError, ValueError):
                    design = {"raw": content, "parse_error": True}
            
            designs.append(design)

        logger.info(f"[{AGENT_NAME}] Generated %d designs", len(designs))
        return designs

    async def _stage_judge_designs(
        self, designs: list[dict], survey: str
    ) -> tuple[int, dict]:
        """Use a judge LLM call to select the best design."""
        valid = [(i, d) for i, d in enumerate(designs) if "error" not in d and "parse_error" not in d]
        if not valid:
            logger.warning(f"[{AGENT_NAME}] No valid designs generated.")
            # Create a synthetic design that explicitly signals failure to reviewers
            # or better, raise an error that triggers a retry or pause.
            err_msg = "Design generation failed or produced invalid JSON. Check LLM logs."
            for d in designs:
                if "error" in d:
                    err_msg = f"Design generation error: {d['error']}"
                    break

            # We return a dummy design that will fail review but with a clear reason
            dummy = {
                "design_rationale": f"CRITICAL FAILURE: {err_msg}",
                "file_manifest": [],
                "implementation_steps": [],
                "failed_generation": True
            }
            return 0, dummy
        if len(valid) == 1:
            return valid[0]

        judge_prompt = (
            "You are a design judge. Compare these design proposals and select the best one.\n"
            "Respond with a JSON object with two keys: selected_index (integer, 0-based) and justification (string).\n\n"
        )
        for orig_idx, design in valid:
            rationale = str(design.get("design_rationale", ""))[:300]
            files = [f.get("path", "") for f in design.get("file_manifest", [])[:6]]
            files_str = ", ".join(files) if files else "(none)"
            judge_prompt += (
                f"\nDesign {orig_idx}:\n"
                f"  {rationale}\n"
                f"  Files: {files_str}\n"
            )

        async def _call_judge(prompt: str) -> tuple[str, str]:
            """Returns (content, finish_reason)."""
            resp = await call_llm(
                [
                    {"role": "system", "content": "You are a design evaluator. Output only JSON. Be concise."},
                    {"role": "user", "content": prompt},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                max_tokens=PLANNING_JUDGE_MAX_TOKENS,
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=AGENT_NAME,
            )
            self._track_tokens(resp)
            choice = resp.get("choices", [{}])[0]
            return (
                choice.get("message", {}).get("content", ""),
                choice.get("finish_reason", ""),
            )

        try:
            content, finish_reason = await _call_judge(judge_prompt)

            # RC2: Judge hit max_tokens during chain-of-thought — retry with a
            # stripped prompt (rationale only, no file lists) rather than triggering
            # a full design retry round.
            if not content and finish_reason == "length":
                logger.warning(
                    f"[{AGENT_NAME}] Judge hit max_tokens (finish_reason=length) — "
                    "retrying with a shorter prompt."
                )
                short_prompt = (
                    "Select the best design from these rationales. "
                    "Respond with JSON: {\"selected_index\": <int>, \"justification\": \"...\"}.\n\n"
                )
                for orig_idx, design in valid:
                    rationale = str(design.get("design_rationale", ""))[:150]
                    short_prompt += f"Design {orig_idx}: {rationale}\n"
                content, finish_reason = await _call_judge(short_prompt)

            if not content:
                logger.warning(
                    f"[{AGENT_NAME}] Judge returned empty content (finish_reason=%s) — "
                    "defaulting to first valid design %d.",
                    finish_reason, valid[0][0],
                )
                return valid[0][0], designs[valid[0][0]]

            result, _ = json.JSONDecoder().raw_decode(content.lstrip())
            idx = int(result.get("selected_index", valid[0][0]))
            if idx < 0 or idx >= len(designs):
                idx = valid[0][0]
        except ShutdownError:
            raise
        except Exception as exc:
            logger.warning(f"[{AGENT_NAME}] Judge call failed (%s), using first valid design %d", exc, valid[0][0])
            idx = valid[0][0]

        return idx, designs[idx]

    # ------------------------------------------------------------------
    # Stage 3: Design Review Panel
    # ------------------------------------------------------------------

    async def _stage_design_review(
        self, design: dict, survey: str
    ) -> list[Vote]:
        """Five parallel reviewers evaluate the winning design.

        Reviewers: coupling, interface, testability, security design, performance.
        Majority (>=3/5) required to pass.
        """
        reviewers = [
            {
                "name": "coupling_reviewer",
                "focus": (
                    "Review for coupling & dependencies: circular deps, over-coupling, "
                    "god objects, missing abstractions. Check dependency graph for issues."
                ),
            },
            {
                "name": "interface_reviewer",
                "focus": (
                    "Review for interface completeness: contract coverage, API documentation, "
                    "data flow explicitness. Every consumes must resolve to a provides."
                ),
            },
            {
                "name": "testability_reviewer",
                "focus": (
                    "Review for testability & safety: test strategy adequacy, destructive "
                    "operation risks, safety rule compliance (no hard deletes, branch isolation)."
                ),
            },
            {
                "name": "security_design_reviewer",
                "focus": (
                    "Review for security concerns IN THE DESIGN before any code is written. "
                    "Look for: authentication/authorization gaps, data flows exposing sensitive "
                    "information, API endpoints lacking security controls, missing encryption for "
                    "sensitive data at rest/transit, injection vulnerabilities in the proposed "
                    "architecture. If the design has fundamental security flaws, vote REJECTED "
                    "and include 'demotion_target: planning' in your justification."
                ),
            },
            {
                "name": "performance_reviewer",
                "focus": (
                    "Review for performance and scalability concerns. Look for: N+1 query "
                    "patterns in the proposed data model, missing caching strategy for expensive "
                    "operations, synchronous blocking in async code paths, unbounded data growth "
                    "(missing pagination/archival), proposed algorithms with poor time/space "
                    "complexity. If the design has fundamental scalability flaws, vote REJECTED "
                    "and include 'demotion_target: planning' in your justification."
                ),
            },
        ]

        # RC3: Skip off-topic reviewers for unit-test or simple tasks to avoid false
        # REJECTED/NOT_SUITABLE signals from perspectives that have no signal to give.
        if _is_unit_test_task(self.task_title, self.task_description):
            reviewers = [r for r in reviewers if r["name"] in _UNIT_TEST_REVIEWER_SUBSET]
            logger.info(
                "[%s] Unit-test task detected — running %d reviewer(s): %s",
                AGENT_NAME, len(reviewers), [r["name"] for r in reviewers],
            )
        elif self._is_simple:
            reviewers = [r for r in reviewers if r["name"] in _SIMPLE_TASK_REVIEWER_SUBSET]
            logger.info(
                "[%s] Simple task — running %d reviewer(s): %s",
                AGENT_NAME, len(reviewers), [r["name"] for r in reviewers],
            )

        design_summary = json.dumps(design, indent=1, ensure_ascii=True)[:6000]
        _arch = self._arch_ctx
        _arch_prefix = (
            f"Task: {self.task_title}\n"
            f"Description: {self.task_description[:600]}\n"
            + (f"{_arch}\n\n" if _arch else "\n")
        )
        _intent_rule = (
            "\n\nIMPORTANT — Respect explicit task intent: If the task description "
            "explicitly specifies an algorithm, approach, or design choice (e.g. 'naive "
            "recursive', 'simple', 'intentionally not using X'), treat that as a binding "
            "constraint set by the task author. Do NOT vote REJECTED on that basis. "
            "Instead vote WARN and explain the tradeoff in your justification so the "
            "author is informed but not blocked."
        )

        reviewer_prompts = []
        for reviewer in reviewers:
            prompt = (
                f"{_arch_prefix}"
                f"You are reviewing a software design from the perspective of: {reviewer['focus']}"
                f"{_intent_rule}\n\n"
                f"Design:\n{design_summary}\n\n"
                "Render your verdict by calling the `submit_work` tool.\n"
                "Use signal='REVIEW_COMPLETE' and provide the following in the tool arguments:\n"
                "- verdict: 'LIKELY' | 'POSSIBLE' | 'WARN' | 'NEEDS_RESEARCH' | 'NOT_SUITABLE' | 'REJECTED'\n"
                "- confidence: <0-100>\n"
                "- justification: '...'\n"
                "\nUse WARN (not REJECTED) when your concern is an opinionated tradeoff that the "
                "task description has already consciously made."
            )
            reviewer_prompts.append(prompt)

        from app.agent.tools import TOOL_SCHEMAS
        submit_work_schema = [s for s in TOOL_SCHEMAS if s["function"]["name"] == "submit_work"]

        # Run reviewers sequentially
        responses = []
        for reviewer, prompt in zip(reviewers, reviewer_prompts):
            try:
                resp = await call_llm(
                    [
                        {"role": "system", "content": "You are a design reviewer. Call submit_work to finish."},
                        {"role": "user", "content": prompt},
                    ],
                    base_url=self.llm_base_url,
                    model=self.llm_model,
                    tools=submit_work_schema,
                    tool_choice={"type": "function", "function": {"name": "submit_work"}},
                    total_timeout_secs=300,
                    task_id=self.task_id,
                    llm_id=self.llm_id,
                    budget_id=self.budget_id,
                    agent_name=AGENT_NAME,
                )
                responses.append(resp)
            except ShutdownError:
                raise
            except Exception as exc:
                responses.append(exc)

        votes: list[Vote] = []
        for i, resp in enumerate(responses):
            reviewer_name = reviewers[i]["name"]
            if isinstance(resp, Exception):
                logger.warning(f"[{AGENT_NAME}] Reviewer '%s' unavailable: %s", reviewer_name, resp)
                votes.append(Vote(
                    stage=reviewer_name,
                    verdict=Verdict.POSSIBLE,
                    confidence=80,
                    justification=f"Reviewer unavailable (LLM timeout or error): {resp}",
                ))
                continue

            self._track_tokens(resp)
            msg = resp.get("choices", [{}])[0].get("message", {})
            tool_calls = msg.get("tool_calls", [])
            
            data = {}
            if tool_calls:
                tc = tool_calls[0]
                try:
                    args = tc.get("function", {}).get("arguments", "{}")
                    data = json.loads(args) if isinstance(args, str) else args
                except (json.JSONDecodeError, ValueError):
                    data = {}
            else:
                content = msg.get("content", "")
                try:
                    data, _ = json.JSONDecoder().raw_decode(content.lstrip())
                except (json.JSONDecodeError, ValueError):
                    data = {}

            verdict_str = str(data.get("verdict", "POSSIBLE")).upper()
            try:
                verdict = Verdict(verdict_str)
            except ValueError:
                verdict = Verdict.POSSIBLE
            
            confidence = int(data.get("confidence", 80))
            lo, hi = verdict.confidence_range
            confidence = max(lo, min(hi, confidence))
            justification = data.get("justification", msg.get("content", ""))

            votes.append(Vote(
                stage=reviewer_name,
                verdict=verdict,
                confidence=confidence,
                justification=justification,
                raw_response=data,
                model=self.llm_model or "",
            ))

        return votes

    # ------------------------------------------------------------------
    # Stage 4: Pitfall Detection
    # ------------------------------------------------------------------

    async def _stage_pitfall_detection(
        self, design: dict, survey: str
    ) -> list[dict]:
        """Deterministic checks + LLM edge case detection."""
        pitfalls: list[dict] = []

        # Deterministic: check dependency graph for cycles
        dep_graph = design.get("dependency_graph", {})
        if dep_graph:
            from app.agent.static_analysis import _detect_cycles
            cycles = _detect_cycles(dep_graph)
            if cycles:
                for cycle in cycles:
                    pitfalls.append({
                        "type": "circular_dependency",
                        "severity": "high",
                        "detail": f"Circular dependency: {' -> '.join(cycle)}",
                    })

        # Deterministic: file path safety
        from app.agent.tools import _assert_safe_path
        for entry in design.get("file_manifest", []):
            path = entry.get("path", "")
            if path:
                try:
                    # Pass path directly — _assert_safe_path uses set_task_git_cwd effective root.
                    _assert_safe_path(path)
                except ValueError as e:
                    pitfalls.append({
                        "type": "unsafe_path",
                        "severity": "critical",
                        "detail": str(e),
                    })

        # LLM: edge case detection
        _arch = self._arch_ctx
        prompt = (
            (f"{_arch}\n\n" if _arch else "")
            + "Analyze this design for potential pitfalls by calling the `submit_work` tool.\n"
            f"{json.dumps(design, indent=1, ensure_ascii=True)[:4000]}\n\n"
            "Look for: edge cases, implicit dependencies, race conditions, "
            "state management issues, migration risks.\n"
            "Use signal='REVIEW_COMPLETE' and provide the 'pitfalls' list in the tool arguments:\n"
            "pitfalls=[{\"type\": \"...\", \"severity\": \"low|medium|high|critical\", \"detail\": \"...\"}]"
        )

        from app.agent.tools import TOOL_SCHEMAS
        submit_work_schema = [s for s in TOOL_SCHEMAS if s["function"]["name"] == "submit_work"]

        try:
            response = await call_llm(
                [
                    {"role": "system", "content": "You are a software quality analyst. Call submit_work to finish."},
                    {"role": "user", "content": prompt},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                tools=submit_work_schema,
                tool_choice={"type": "function", "function": {"name": "submit_work"}},
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=AGENT_NAME,
            )
            self._track_tokens(response)
            msg = response.get("choices", [{}])[0].get("message", {})
            tool_calls = msg.get("tool_calls", [])
            
            data = {}
            if tool_calls:
                tc = tool_calls[0]
                try:
                    args = tc.get("function", {}).get("arguments", "{}")
                    data = json.loads(args) if isinstance(args, str) else args
                except (json.JSONDecodeError, ValueError):
                    data = {}
            else:
                content = msg.get("content", "")
                try:
                    data, _ = json.JSONDecoder().raw_decode(content.lstrip())
                except (json.JSONDecodeError, ValueError):
                    data = {}

            pitfalls.extend(data.get("pitfalls", []))
        except Exception as e:
            logger.warning(f"[{AGENT_NAME}] Pitfall LLM check failed: %s", e)

        return pitfalls

    # ------------------------------------------------------------------
    # Stage 5: Plan Consolidation
    # ------------------------------------------------------------------

    async def _stage_consolidation(
        self, design: dict, pitfalls: list[dict], survey: str
    ) -> dict:
        """Merge the winning design with pitfall mitigations using submit_work."""
        if not pitfalls:
            return design

        _arch = self._arch_ctx
        prompt = (
            (f"{_arch}\n\n" if _arch else "")
            + "You have a winning design and identified pitfalls. "
            "Produce a consolidated final design that incorporates mitigations "
            "for the identified pitfalls by calling the `submit_work` tool.\n\n"
            "Use signal='DESIGN_COMPLETE' and provide the full design JSON in the tool arguments.\n"
            f"Original design:\n{json.dumps(design, indent=1, ensure_ascii=True)[:4000]}\n\n"
            f"Pitfalls:\n{json.dumps(pitfalls, indent=1, ensure_ascii=True)[:2000]}"
        )

        from app.agent.tools import TOOL_SCHEMAS
        submit_work_schema = [s for s in TOOL_SCHEMAS if s["function"]["name"] == "submit_work"]

        try:
            response = await call_llm(
                [
                    {"role": "system", "content": "You are a software architect. Call submit_work to finish."},
                    {"role": "user", "content": prompt},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                tools=submit_work_schema,
                tool_choice={"type": "function", "function": {"name": "submit_work"}},
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=AGENT_NAME,
            )
            self._track_tokens(response)
            msg = response.get("choices", [{}])[0].get("message", {})
            tool_calls = msg.get("tool_calls", [])
            
            result = {}
            if tool_calls:
                tc = tool_calls[0]
                try:
                    args = tc.get("function", {}).get("arguments", "{}")
                    result = json.loads(args) if isinstance(args, str) else args
                except (json.JSONDecodeError, ValueError):
                    result = {}
            else:
                content = msg.get("content", "")
                try:
                    result, _ = json.JSONDecoder().raw_decode(content.lstrip())
                except (json.JSONDecodeError, ValueError):
                    result = {}
            
            return result or design
        except Exception as e:
            logger.warning(f"[{AGENT_NAME}] Consolidation failed: %s. Using original design.", e)
            return design

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _check_scope(self, design: dict) -> str | None:
        """Return a reason string if the design is too large, else None."""
        files = design.get("file_manifest", [])
        steps = design.get("implementation_steps", [])
        if len(files) > PLANNING_MAX_FILES:
            return (
                f"Design spans {len(files)} files (limit {PLANNING_MAX_FILES}). "
                "Too broad for a single implementation task — should be subdivided."
            )
        if len(steps) > PLANNING_MAX_STEPS:
            return (
                f"Design has {len(steps)} implementation steps (limit {PLANNING_MAX_STEPS}). "
                "Too complex for a single task — should be subdivided."
            )
        return None

    def _track_tokens(self, response: dict) -> None:
        usage = response.get("usage", {})
        self._total_prompt += usage.get("prompt_tokens", 0)
        self._total_completion += usage.get("completion_tokens", 0)

    def _build_result(
        self, consolidated: dict, all_designs: list[dict],
        selected_index: int, review_votes: list[Vote],
        pitfalls: list[dict], survey: str,
        passed: bool = True,
    ) -> PlanningResult:
        # Parse file manifest
        file_manifest = []
        for entry in consolidated.get("file_manifest", []):
            file_manifest.append(FileManifestEntry(
                path=entry.get("path", ""),
                action=entry.get("action", "create"),
                purpose=entry.get("purpose", ""),
                estimated_lines=entry.get("estimated_lines", 0),
                depends_on=entry.get("depends_on", []),
            ))

        # Parse interface contracts
        contracts = []
        for c in consolidated.get("interface_contracts", []):
            contracts.append(InterfaceContract(
                component=c.get("component", ""),
                provides=c.get("provides", []),
                consumes=c.get("consumes", []),
                invariants=c.get("invariants", []),
            ))

        # Parse test strategy
        test_strategy = []
        for t in consolidated.get("test_strategy", []):
            test_strategy.append(TestStrategyEntry(
                component=t.get("component", ""),
                test_file=t.get("test_file", ""),
                test_cases=t.get("test_cases", []),
                fixtures=t.get("fixtures", []),
            ))

        # Parse implementation steps
        steps = []
        for s in consolidated.get("implementation_steps", []):
            steps.append(ImplementationStep(
                order=s.get("order", 0),
                component=s.get("component", ""),
                files=s.get("files", []),
                description=s.get("description", ""),
                depends_on=s.get("depends_on", []),
                estimated_context_tokens=s.get("estimated_context_tokens", 0),
            ))

        return PlanningResult(
            task_id=self.task_id,
            design_rationale=consolidated.get("design_rationale", ""),
            file_manifest=file_manifest,
            dependency_graph=consolidated.get("dependency_graph", {}),
            interface_contracts=contracts,
            test_strategy=test_strategy,
            implementation_steps=sorted(steps, key=lambda s: s.order),
            pitfalls_identified=pitfalls,
            review_votes=review_votes,
            best_of_n_designs=all_designs,
            selected_design_index=selected_index,
            confidence=80 if passed else 0,
            prompt_tokens=self._total_prompt,
            completion_tokens=self._total_completion,
        )

    def _store_result(self, result: PlanningResult) -> None:
        """Persist PlanningResult to the database.

        If ``self.run_row_id`` is set (i.e. the caller pre-created an
        ``in_progress`` row), update that row in-place so the row ID stays
        stable.  Otherwise fall back to creating a new row (scheduler path).
        """
        kwargs = dict(
            file_manifest=json.dumps([asdict(f) for f in result.file_manifest]),
            dependency_graph=json.dumps(result.dependency_graph),
            interface_contracts=json.dumps([asdict(c) for c in result.interface_contracts]),
            test_strategy=json.dumps([asdict(t) for t in result.test_strategy]),
            implementation_steps=json.dumps([asdict(s) for s in result.implementation_steps]),
            pitfalls_identified=json.dumps(result.pitfalls_identified),
            review_votes=json.dumps([
                {"stage": v.stage, "verdict": v.verdict.value, "confidence": v.confidence,
                 "justification": v.justification}
                for v in result.review_votes
            ]),
            best_of_n_designs=json.dumps(result.best_of_n_designs),
            selected_design_index=result.selected_design_index,
            confidence=result.confidence,
            prompt_tokens=result.prompt_tokens,
            completion_tokens=result.completion_tokens,
            status='active',
        )
        try:
            if self.run_row_id is not None:
                from app.database import update_planning_result
                from app.database.session import SessionLocal as _SL
                _db = _SL()
                try:
                    update_planning_result(_db, self.run_row_id, **kwargs)
                finally:
                    _db.close()
            else:
                from app.database import create_planning_result
                create_planning_result(task_id=result.task_id, **kwargs)
        except Exception as e:
            logger.error(f"[{AGENT_NAME}] Failed to store result: %s", e)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def run_planning_pipeline(
    task_id: str,
    task_title: str,
    task_description: str,
    all_tasks: list[dict],
    *,
    llm_base_url: str | None = None,
    llm_model: str | None = None,
    llm_id: int | None = None,
    budget_id: int | None = None,
    max_context: int | None = None,
    project_path: str | None = None,
    project_name: str | None = None,
    run_row_id: int | None = None,
) -> dict:
    """Run the full planning pipeline and return a result dict."""
    if project_path is not None:
        from app.agent.tools import set_task_git_cwd
        set_task_git_cwd(project_path)
    pipeline = PlanningPipeline(
        task_id=task_id,
        task_title=task_title,
        task_description=task_description,
        all_tasks=all_tasks,
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_id=llm_id,
        budget_id=budget_id,
        max_context=max_context,
        run_row_id=run_row_id,
        project_name=project_name,
        project_root=project_path,
    )
    result = await pipeline.run()
    votes_list = [
        {"stage": v.stage, "verdict": v.verdict.value, "confidence": v.confidence,
         "justification": v.justification}
        for v in result.review_votes
    ]
    # Scope-too-large: signal subdivision before confidence check
    if result.scope_verdict:
        return {
            "task_id": result.task_id,
            "outcome": "subdivide",
            "scope_reason": result.scope_verdict,
            "design_rationale": result.design_rationale,
            "file_manifest": [asdict(f) for f in result.file_manifest],
            "survey_summary": result.survey_summary,
            "total_prompt_tokens": result.prompt_tokens,
            "total_completion_tokens": result.completion_tokens,
            "votes": votes_list,
        }
    return {
        "task_id": result.task_id,
        "outcome": "passed" if result.confidence >= 60 else "rejected",
        "design_rationale": result.design_rationale,
        "file_manifest": [asdict(f) for f in result.file_manifest],
        "dependency_graph": result.dependency_graph,
        "interface_contracts": [asdict(c) for c in result.interface_contracts],
        "test_strategy": [asdict(t) for t in result.test_strategy],
        "implementation_steps": [asdict(s) for s in result.implementation_steps],
        "pitfalls_identified": result.pitfalls_identified,
        "selected_design_index": result.selected_design_index,
        "confidence": result.confidence,
        "total_prompt_tokens": result.prompt_tokens,
        "total_completion_tokens": result.completion_tokens,
        "votes": votes_list,
    }
