"""
app/agent/planning.py
---------------------
Planning pipeline for the PLANNING stage.

Sub-stages:
  1. Codebase Survey - agentic loop (read-only tools, max N turns)
  2. Best-of-N Design Generation - N parallel structured LLM calls
  3. Design Review Panel - 3 parallel LLM reviewers
  4. Pitfall Detection - deterministic + 1 LLM call
  5. Plan Consolidation - 1 LLM call to merge winner + pitfall mitigations

Output: PlanningResult stored in planning_results table.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from dataclasses import asdict, dataclass, field
from typing import Any

from app.agent.config import (
    PLANNING_BEST_OF_N,
    PLANNING_JUDGE_MAX_TOKENS,
    PLANNING_MAX_DESIGN_RETRIES,
    PLANNING_SURVEY_MAX_TURNS,
    PLANNING_MAX_FILES,
    PLANNING_MAX_STEPS,
    PROJECT_ROOT,
    check_context_saturation,
)
from app.agent.llm_client import call_llm, is_shutting_down, sanitize_user_content, ShutdownError
from app.agent.mathlib_cheatsheet import format_for_prompt as _cheatsheet
from app.agent.verdicts import Vote, Verdict, tally_votes

logger = logging.getLogger(__name__)
AGENT_NAME = "Planning Pipeline"

# ---------------------------------------------------------------------------
# Design personas — each proposal in the Best-of-N pool is generated by a
# different architect persona with a distinct primary concern.  The same task
# description and codebase survey are sent to every persona; variance comes
# from the framing, not from sampling hyperparameters.
#
# If PLANNING_BEST_OF_N > len(_DESIGN_PERSONAS), personas repeat round-robin.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Reviewer relevance — unit-test tasks only need a subset of the review panel.
# Performance and security reviewers have no signal to give on "write N pytest
# assertions for a dataclass"; running them wastes LLM slots and produces
# NOT_SUITABLE verdicts (now treated as abstentions) or false REJECTED signals.
# ---------------------------------------------------------------------------

_UNIT_TEST_REVIEWER_SUBSET = frozenset({
    "coupling_reviewer",
    "interface_reviewer",
    "testability_reviewer",
})

_UNIT_TEST_TITLE_PATTERNS = ("test_", "test ", "tests for", "testcare", "testplant", "testcreate", "testupdate", "testdelete")
_UNIT_TEST_DESC_PATTERNS = ("@pytest", "def test_", "pytest.fixture", "assert ", "dataclass", " enum ", "unit test")

# Formal-proof tasks only need reviewers that can reason about proof structure and
# verification strategy.  Security and performance reviewers have nothing to say about
# theorem proving and will emit false NOT_SUITABLE / REJECTED signals.
_PROOF_REVIEWER_SUBSET = frozenset({
    "coupling_reviewer",      # repurposed: lemma dependency graph, no circular proofs
    "testability_reviewer",   # repurposed: verification strategy, lake build, no sorry
})

_PROOF_KEYWORDS = (
    "lean4", "lean 4", "coq", "isabelle", "agda", "idris",
    "theorem", "lemma", "proof", "mathlib", "lake build",
    " sorry", "formal verification", "tactic", "tactic proof",
    "fermat", "prime", "zmod", "nat.prime",
)


def _is_proof_task(title: str, description: str) -> bool:
    """Return True when heuristics indicate a formal-proof / theorem-proving task."""
    combined = (title + " " + (description or "")).lower()
    return any(kw in combined for kw in _PROOF_KEYWORDS)


_TEMPLATE_DOMAIN_MAP: dict[str, str] = {
    "mathematics / proof exploration": "proof",
    "mathematics/proof exploration": "proof",
    "novel writing": "writing",
    "research report": "research",
    "data analysis": "data_analysis",
    "bug triage": "bug_triage",
    "software development": "software",
    "overnight generation": "writing",
    "overnight story factory": "writing",
}


def _get_domain(
    pipeline_template_id: int | None,
    title: str,
    description: str,
) -> str:
    """Return the planning domain string for this task.

    Priority:
    1. Map pipeline_template_id → template name → domain
    2. Proof keyword heuristics
    3. Default: "software"
    """
    if pipeline_template_id is not None:
        try:
            from app.database.session import SessionLocal as _SL
            import sqlalchemy as _sa
            db = _SL()
            try:
                row = db.execute(
                    _sa.text("SELECT name FROM pipeline_templates WHERE id = :id"),
                    {"id": pipeline_template_id},
                ).fetchone()
                if row:
                    name_lower = (row[0] or "").lower().strip()
                    if name_lower in _TEMPLATE_DOMAIN_MAP:
                        return _TEMPLATE_DOMAIN_MAP[name_lower]
                    # Partial match fallback
                    for key, domain in _TEMPLATE_DOMAIN_MAP.items():
                        if key in name_lower or name_lower in key:
                            return domain
            finally:
                db.close()
        except Exception:
            pass
    if _is_proof_task(title, description):
        return "proof"
    return "software"


def _is_unit_test_task(title: str, description: str) -> bool:
    """Return True when heuristics indicate a pure unit-test writing task."""
    title_l = title.lower()
    if any(title_l.startswith(p) or p in title_l for p in _UNIT_TEST_TITLE_PATTERNS):
        return True
    desc_l = (description or "").lower()
    return any(p in desc_l for p in _UNIT_TEST_DESC_PATTERNS)


# ---------------------------------------------------------------------------
# Complexity classification — simple tasks get a lite reviewer panel and a
# smaller design pool (2 proposals instead of 5).  This avoids the full
# gauntlet for trivially-scoped greenfield scripts.
# ---------------------------------------------------------------------------

_SIMPLE_TASK_REVIEWER_SUBSET = frozenset({
    "coupling_reviewer",
    "testability_reviewer",
})

_SIMPLE_KEYWORDS = (
    "greenfield", "simple", "naive", "single file", "single function",
    "one function", "write a function", "add a function", "basic",
    "minimal", "straightforward", "write a script", "small utility",
)


def _is_simple_task(title: str, description: str, survey: str = "") -> bool:
    """Return True when heuristics indicate a low-complexity task.

    Simple tasks skip the security/performance reviewers (they have nothing
    to say about a 30-line function) and generate only 2 design proposals
    instead of the full PLANNING_BEST_OF_N pool.
    """
    combined = (title + " " + (description or "")).lower()
    if any(kw in combined for kw in _SIMPLE_KEYWORDS):
        return True
    # Short description almost always means narrow scope
    if len(description or "") < 150:
        return True
    # Survey explicitly says empty/greenfield project
    survey_l = (survey or "").lower()
    if "greenfield" in survey_l or ("empty" in survey_l and "project" in survey_l):
        return True
    return False


def _extract_spec_constraints(description: str) -> str:
    """Extract explicit algorithmic/design constraints from a task description.

    Returns a bulleted list of constraints to inject into the design prompt,
    or an empty string if none are detected.
    """
    if not description:
        return ""

    desc_lower = description.lower()
    constraints: list[str] = []

    constraint_signals = [
        ("naive recursive", "Algorithm must be naive recursive — no memoization, no iteration"),
        ("naive recursion", "Algorithm must be naive recursive — no memoization, no iteration"),
        ("no memoization", "Memoization is explicitly forbidden"),
        ("without memoization", "Memoization is explicitly forbidden"),
        ("no caching", "Caching is explicitly forbidden"),
        ("without caching", "Caching is explicitly forbidden"),
        ("simple recursive", "Algorithm must be simple/naive recursive"),
        ("do not use", "Explicit exclusion present — see description"),
        ("must not use", "Explicit exclusion present — see description"),
        ("intentionally not", "Intentional design constraint present — see description"),
        ("explicitly", "Explicit constraint present — see description"),
        ("keep it simple", "Implementation must remain simple — no unnecessary abstractions"),
        ("greenfield", "This is a greenfield project — start from scratch, minimal structure only"),
    ]

    for signal, label in constraint_signals:
        if signal in desc_lower:
            constraints.append(f"• {label}")

    if not constraints:
        return ""

    return (
        "The task description contains BINDING design constraints:\n"
        + "\n".join(constraints)
        + "\n\nYou MUST respect these constraints. Do not 'improve' the design beyond what is asked."
        + "\n\nIf the existing codebase already uses a forbidden approach (e.g. memoization exists"
        " but is forbidden), write design_rationale to describe ONLY the target implementation."
        " One sentence naming what you are replacing is fine (e.g. 'Replaces the existing"
        " memoized implementation with naive recursion.'). After that, describe the target"
        " design only — do not repeat the forbidden approach name."
    )


def _scan_existing_files(project_root: str, survey_text: str) -> list[str]:
    """Return a list of existing source files in the project root (up to 30).

    Used to warn the design LLM that the project is not greenfield.
    Skips hidden dirs, venv, __pycache__, node_modules.
    """
    import os

    _SKIP_DIRS = frozenset({
        "venv", ".venv", "env", "__pycache__", "node_modules", ".git",
        ".archive", ".maestro-worktrees", "dist", "build", ".eggs",
        "site-packages", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    })
    found: list[str] = []

    try:
        for root, dirs, files in os.walk(project_root):
            dirs[:] = [
                d for d in dirs
                if d not in _SKIP_DIRS and not d.startswith(".")
            ]
            rel_root = os.path.relpath(root, project_root)
            for fname in files:
                if fname.startswith("."):
                    continue
                rel = os.path.join(rel_root, fname).replace("\\", "/")
                if rel.startswith("./"):
                    rel = rel[2:]
                found.append(rel)
                if len(found) >= 30:
                    return found
    except Exception:
        pass

    return found


# Design personas for formal-proof / theorem-proving tasks.  Replaces the SW-dev
# personas when _is_proof_task() returns True.
_PROOF_DESIGN_PERSONAS: list[tuple[str, str]] = [
    (
        "Mathematical Rigor & Completeness",
        "Your primary concern is mathematical correctness and completeness. "
        "Every case must be covered, no sorry placeholders are acceptable in the final proof, "
        "and the argument must be logically watertight. Identify which Mathlib lemmas are "
        "available and sufficient; do not assume lemmas exist without evidence. "
        "In your design_rationale, explain the mathematical strategy and why it is complete.",
    ),
    (
        "Lean4 Tactics & Mathlib Integration",
        "Your primary concern is idiomatic use of Lean4 and Mathlib. "
        "Choose tactic blocks that are concise and well-supported by existing Mathlib infrastructure. "
        "Prefer `decide`, `norm_num`, `ring`, `simp`, `omega`, `exact?`, `apply?` where applicable. "
        "Identify the precise Mathlib import paths needed. "
        "In your design_rationale, name the specific lemmas or tactics you plan to use and why.",
    ),
    (
        "Proof Structure & Readability",
        "Your primary concern is proof structure and long-term readability. "
        "Break the proof into named helper lemmas with clear statements. "
        "Use meaningful names and add doc-comments explaining the mathematical intent. "
        "The proof should be maintainable: a future contributor should be able to see "
        "immediately what each lemma asserts and why the overall structure works. "
        "In your design_rationale, describe the decomposition into sub-lemmas and the "
        "narrative flow of the proof.",
    ),
    (
        "Build & Verification Strategy",
        "Your primary concern is ensuring the deliverable compiles and passes all checks. "
        "Plan for a zero-error `lake build`: resolve all imports, handle universe levels, "
        "and anticipate type-class resolution issues. Define the verification steps the "
        "implementation agent must run (lake build, lean --check, etc.). "
        "In your design_rationale, list the exact build commands, expected output, and "
        "how you will confirm zero sorry and zero errors.",
    ),
    (
        "Lean4 Build & Import Strategy",
        "Your primary concern is import ordering, namespace hygiene, and build-system correctness. "
        "Identify the exact `import Mathlib.*` paths required, check for name collisions with "
        "existing Mathlib declarations, and flag universe-level constraints that could cause "
        "unexpected errors. Ensure the `lakefile.lean` dependencies are correct and that "
        "`lake build` will succeed without any `sorry`. "
        "In your design_rationale, list each import path with justification, identify any "
        "Mathlib namespace conflicts, and describe how universe polymorphism is handled.",
    ),
]

_DESIGN_PERSONAS: list[tuple[str, str]] = [
    (
        "Correctness & Testability",
        "Your primary concern is correctness and testability. "
        "Design for explicit, predictable error handling and well-defined failure modes. "
        "Create clean test seams — each component must be independently verifiable without "
        "needing to wire up the whole system. Prefer explicit over implicit. "
        "In your design_rationale, explain how the structure makes the system easy to test "
        "and how errors propagate clearly.",
    ),
    (
        "Security & Defensive Robustness",
        "Your primary concern is security and defensive design. "
        "Minimise the attack surface. Validate all inputs at every trust boundary. "
        "Use safe defaults and fail closed on unexpected conditions. "
        "Avoid over-privileged components — each module should access only what it needs. "
        "Think through what can go wrong and design around it. "
        "In your design_rationale, explain the key trust boundaries, what is validated where, "
        "and how the design degrades safely under adversarial or unexpected input.",
    ),
    (
        "Code Clarity & Codebase Consistency",
        "Your primary concern is code clarity and consistency with the existing codebase. "
        "Study the survey carefully: match the naming conventions, file layout, module "
        "structure, and idioms already present. A contributor familiar with the existing code "
        "should be able to predict every design choice you make before reading it. "
        "Prefer conventional structure over clever structure. Avoid introducing new patterns "
        "when existing ones already solve the problem. "
        "In your design_rationale, describe specifically how your design mirrors the patterns "
        "you observed in the codebase survey.",
    ),
    (
        "Performance & Operational Efficiency",
        "Your primary concern is performance and resource efficiency. "
        "Minimise unnecessary computation, I/O, and database round-trips on the critical path. "
        "Consider caching strategies and async opportunities that reduce latency where it matters. "
        "Avoid premature abstraction that adds indirection without benefit. "
        "Design data flows so that the common case is fast; handle the slow path explicitly. "
        "In your design_rationale, identify the performance-critical paths and explain the "
        "specific choices that keep them efficient.",
    ),
    (
        "Clean Architecture & Boundary Clarity",
        "Your primary concern is clean architecture and strict separation of concerns. "
        "Each module must have one clear, narrow responsibility. Define explicit interface "
        "contracts between components — what each provides, what it consumes, what invariants "
        "it upholds. Minimise coupling: a change in one area should not ripple unexpectedly. "
        "Design the system so its structure is self-evident from the file layout alone. "
        "In your design_rationale, explain exactly where you drew each boundary and why each "
        "component owns the responsibilities it does.",
    ),
]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class FileManifestEntry:
    path: str
    action: str  # create | modify | delete
    purpose: str
    estimated_lines: int = 0
    depends_on: list[str] = field(default_factory=list)


@dataclass(slots=True)
class InterfaceContract:
    component: str
    provides: list[str] = field(default_factory=list)
    consumes: list[str] = field(default_factory=list)
    invariants: list[str] = field(default_factory=list)


@dataclass(slots=True)
class TestStrategyEntry:
    component: str
    test_file: str
    test_cases: list[str] = field(default_factory=list)
    fixtures: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ImplementationStep:
    order: int
    component: str
    files: list[str] = field(default_factory=list)
    description: str = ""
    depends_on: list[str] = field(default_factory=list)
    estimated_context_tokens: int = 0


@dataclass(slots=True)
class PlanningResult:
    task_id: str
    design_rationale: str = ""
    file_manifest: list[FileManifestEntry] = field(default_factory=list)
    dependency_graph: dict[str, list[str]] = field(default_factory=dict)
    interface_contracts: list[InterfaceContract] = field(default_factory=list)
    test_strategy: list[TestStrategyEntry] = field(default_factory=list)
    implementation_steps: list[ImplementationStep] = field(default_factory=list)
    pitfalls_identified: list[dict] = field(default_factory=list)
    review_votes: list[Vote] = field(default_factory=list)
    best_of_n_designs: list[dict] = field(default_factory=list)
    selected_design_index: int = 0
    confidence: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    scope_verdict: str = ""      # non-empty when design scope is too large
    survey_summary: str = ""     # codebase survey result, passed to subdivision


# ---------------------------------------------------------------------------
# Read-only tools for codebase survey
# ---------------------------------------------------------------------------

SURVEY_TOOLS = [
    "read_file", "count_lines",
    "search_files", "find_files", "list_directory",
    "git_log", "git_blame",
    "get_task", "list_tasks",
    "submit_work",
]

# Extra tools unlocked for formal-proof / theorem-proving survey phases.
_PROOF_SURVEY_EXTRA_TOOLS = [
    "search_mathlib", "search_arxiv", "search_oeis", "list_mathlib_topics",
]


def _get_survey_tool_schemas(*, is_proof: bool = False) -> list[dict]:
    """Return OpenAI-format tool schemas for the survey agent."""
    from app.agent.tools import TOOL_SCHEMAS
    allowed = set(SURVEY_TOOLS)
    if is_proof:
        allowed.update(_PROOF_SURVEY_EXTRA_TOOLS)
    return [s for s in TOOL_SCHEMAS if s["function"]["name"] in allowed]


# ---------------------------------------------------------------------------
# Pipeline class
# ---------------------------------------------------------------------------

class PlanningPipeline:
    """Orchestrates the planning pipeline for a single task."""

    def __init__(
        self,
        task_id: str,
        task_title: str,
        task_description: str,
        all_tasks: list[dict],
        *,
        llm_base_url: str | None = None,
        llm_model: str | None = None,
        llm_id: int | None = None,
        budget_id: int | None = None,
        max_context: int | None = None,
        run_row_id: int | None = None,
        project_name: str | None = None,
        project_root: str | None = None,
        prior_failure_context: list | None = None,
    ):
        self.task_id = task_id
        self.task_title = task_title
        self.task_description = task_description
        self.all_tasks = all_tasks
        self.llm_base_url = llm_base_url
        self.llm_model = llm_model
        self.llm_id = llm_id
        self.budget_id = budget_id
        self.max_context = max_context
        self.run_row_id = run_row_id
        self.project_name = project_name
        self.project_root = project_root
        self.prior_failure_context = prior_failure_context or []
        self._total_prompt = 0
        self._total_completion = 0
        self._stage_cfg: dict = {}
        try:
            from app.agent.pipeline_router import get_stage_config as _gsc
            _sc = _gsc(task_id)
            self._stage_cfg = (_sc.config or {}) if _sc else {}
        except Exception:
            pass
        # If stage config defines per-persona overrides, build a matching list of (label, concern) tuples
        _cfg_personas = self._stage_cfg.get("personas")
        self._config_personas: list[tuple[str, str]] | None = (
            [(p["name"], p["system_prompt"]) for p in _cfg_personas if p.get("name") and p.get("system_prompt")]
            if _cfg_personas else None
        )
        # Set in run() after the survey, used by _stage_design_review
        self._is_simple: bool = False
        self._is_proof: bool = False
        self._effective_best_of_n: int = PLANNING_BEST_OF_N
        # Lazily computed architecture context (cached on first access)
        self.__arch_ctx: str | None = None

    @property
    def _arch_ctx(self) -> str:
        if self.__arch_ctx is None:
            if not self.project_name:
                self.__arch_ctx = ""
            else:
                try:
                    from app.agent.project_snapshot import build_architecture_context
                    self.__arch_ctx = build_architecture_context(
                        self.project_name, agent_type="planning"
                    ) or ""
                except Exception:
                    self.__arch_ctx = ""
        return self.__arch_ctx

    # run() removed — planning pipeline is now driven by individual node executors
    # (planning_survey_node, multiplier_node, pitfall_node, consolidation_node,
    # planning_gate_node) registered in scheduler.py.  All remaining methods below
    # are still used by those executors via run_planning_survey / run_pitfall_detection
    # / run_consolidation_and_store entry points.

    # ------------------------------------------------------------------
    # Stage 1: Codebase Survey (entry: run_planning_survey)
    # ------------------------------------------------------------------
    #
    # NOTE: The original Stage 1 comment block has been merged here.
    # _stage_codebase_survey is called directly by run_planning_survey().
    # ------------------------------------------------------------------

    async def _stage_codebase_survey(self) -> str:
        """Run an agentic loop with read-only tools to survey the codebase."""
        from app.agent.tools import dispatch_tool, _restrict_reads_to_root as _survey_root_flag

        _arch = self._arch_ctx

        _task_ctx = f"\n\nTask: {self.task_title}\nDescription: {self.task_description}" + (f"\n\n{_arch}" if _arch else "")
        if self._is_proof:
            _base = self._stage_cfg.get("system_prompt_proof") or (
                "You are a formal-proof surveyor. Your job is to gather the information "
                "a proof designer needs: what Mathlib already provides, what the mathematical "
                "strategy should be, and what project structure (if any) already exists.\n\n"
                "WORKFLOW:\n"
                "1. Check whether any Lean/proof files already exist with list_directory / find_files.\n"
                "2. If the project is EMPTY (no .lean files), that is EXPECTED — skip immediately to step 3.\n"
                "3. Call list_mathlib_topics() to see available topic areas, then use search_mathlib for the "
                "specific lemmas you need. For Fermat's Little Theorem or modular arithmetic tasks, "
                "search for terms like 'ZMod', 'Finset.card', 'ZMod.pow_card_sub_one_eq_one', "
                "'Nat.Prime', 'Finset.prod_pow_eq_pow_sum'. "
                "Run 2-4 targeted searches covering the key lemmas you expect to need.\n"
                "4. Optionally use search_arxiv if a literature reference would sharpen the proof strategy.\n"
                "5. Once you have identified the relevant Mathlib lemmas and understand the proof strategy, "
                "call submit_work(signal='ACCEPTED', summary='<your findings>') to finish the survey.\n\n"
                "GREENFIELD SHORTCUT — if list_directory shows no .lean files, do NOT keep searching "
                "the filesystem. Go directly to list_mathlib_topics(), then search_mathlib."
            )
            # Cheatsheet is always appended (dynamic, not stored in stage config)
            system_prompt = _base + "\n\n" + _cheatsheet() + _task_ctx
            user_content = (
                "Survey the proof environment. Check for existing .lean files, then search Mathlib "
                "for the key lemmas this proof will need. When done, call submit_work to finish."
            )
        else:
            _base = self._stage_cfg.get("system_prompt") or (
                "You are a codebase surveyor. Your job is to understand the existing code "
                "structure relevant to the following task.\n\n"
                "WORKFLOW:\n"
                "1. Use tools to read 3-8 key files most relevant to the task.\n"
                "2. Once you have a clear picture of the existing structure, STOP reading "
                "and synthesize your findings.\n"
                "3. Call submit_work(signal='ACCEPTED', summary='<your findings>') to finish. "
                "Alternatively, output a message starting with 'SURVEY_COMPLETE:' followed by "
                "your summary.\n\n"
                "GREENFIELD SHORTCUT — if list_directory shows the project is empty, call "
                "submit_work immediately with summary='Greenfield project — no existing files.'\n\n"
                "SYNTHESIS TRIGGERS — finish when ANY of these are true:\n"
                "- You have read 5+ files and understand the relevant interfaces.\n"
                "- You have confirmed the relevant modules and their responsibilities.\n"
                "- You have identified what needs to change and what can be reused."
            )
            system_prompt = _base + _task_ctx
            user_content = (
                "Survey the codebase. Focus only on files most relevant to this task. "
                "Read 3-8 key files, then call submit_work to finish. "
                "Do not exhaustively read every file — stop once you understand the key structure."
            )

        messages: list[dict] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]

        tool_schemas = _get_survey_tool_schemas(is_proof=self._is_proof)
        survey_result = ""
        content = ""
        _ctx_warned: set[float] = set()
        _turn_warned: set[int] = set()
        
        # Repetition guard: track (tool_name, arguments_hash)
        _tool_call_history: set[tuple[str, str]] = set()

        # RC5: Restrict absolute-path reads to this project's root for the survey phase.
        # Prevents the LLM from wandering into unrelated project trees on the same machine.
        _root_token = _survey_root_flag.set(True)
        try:
            for turn in range(PLANNING_SURVEY_MAX_TURNS):
                if is_shutting_down():
                    raise ShutdownError("Server is shutting down")

                # Context saturation check
                if check_context_saturation(
                    response.get("usage", {}).get("prompt_tokens", 0) if turn > 0 else 0,
                    self.max_context or 0,
                    _ctx_warned,
                    messages,
                ):
                    logger.warning("Planning survey context saturation (turn %d) - terminating", turn)
                    break

                # Turn saturation check
                from app.agent.config import check_turn_saturation
                if check_turn_saturation(
                    turn, PLANNING_SURVEY_MAX_TURNS, _turn_warned, messages
                ):
                    pass

                response = await call_llm(
                    messages,
                    base_url=self.llm_base_url,
                    model=self.llm_model,
                    tools=tool_schemas,
                    task_id=self.task_id,
                    llm_id=self.llm_id,
                    budget_id=self.budget_id,
                    agent_name=AGENT_NAME,
                )

                self._track_tokens(response)

                # Context saturation check
                if check_context_saturation(
                    response.get("usage", {}).get("prompt_tokens", 0),
                    self.max_context or 0,
                    _ctx_warned,
                    messages,
                ):
                    logger.warning(f"[{AGENT_NAME}] Survey context saturation (turn %d) - terminating", turn + 1)
                    break
                choice = response.get("choices", [{}])[0]
                msg = choice.get("message", {})
                content = msg.get("content", "")
                tool_calls = msg.get("tool_calls", [])

                messages.append(msg)

                # Check for completion signal
                if content and "SURVEY_COMPLETE:" in content:
                    survey_result = content.split("SURVEY_COMPLETE:", 1)[1].strip()
                    logger.info(f"[{AGENT_NAME}] Survey completed at turn %d/%d",
                                turn + 1, PLANNING_SURVEY_MAX_TURNS)
                    break

                # Dispatch tool calls
                if tool_calls:
                    for tc in tool_calls:
                        fn_name = tc["function"]["name"]
                        fn_args_raw = tc["function"]["arguments"]
                        
                        # Guard: Check for repeated tool calls with same args
                        args_str = json.dumps(fn_args_raw, sort_keys=True)
                        call_key = (fn_name, args_str)
                        if call_key in _tool_call_history:
                            logger.warning(
                                f"[{AGENT_NAME}] Repetitive tool call detected: %s(%s). Breaking survey loop.",
                                fn_name, args_str
                            )
                            survey_result = content or "Survey terminated due to tool call loop."
                            break
                        _tool_call_history.add(call_key)

                        try:
                            fn_args = fn_args_raw if isinstance(fn_args_raw, dict) else json.loads(fn_args_raw)
                        except json.JSONDecodeError as e:
                            logger.warning(
                                f"[{AGENT_NAME}] Malformed tool call args for %s: %s — skipping call",
                                fn_name, e,
                            )
                            messages.append({
                                "role": "tool",
                                "tool_call_id": tc["id"],
                                "content": f"Error: malformed arguments JSON — {e}",
                            })
                            continue
                        try:
                            result = dispatch_tool(fn_name, fn_args)
                        except Exception as e:
                            result = f"Error: {e}"
                        result_str = str(result)

                        # submit_work terminal signal — extract summary and end survey.
                        # Parse from untruncated `result` so a long summary doesn't
                        # silently truncate the JSON and cause the loop to continue.
                        if fn_name == "submit_work":
                            try:
                                _terminal = json.loads(str(result))
                                if _terminal.get("__maestro_terminal__"):
                                    survey_result = _terminal.get("summary", result_str)
                                    logger.info(
                                        "[%s] Survey ended via submit_work at turn %d",
                                        AGENT_NAME, turn + 1,
                                    )
                                    messages.append({
                                        "role": "tool",
                                        "tool_call_id": tc["id"],
                                        "content": result_str,
                                    })
                                    break
                            except (json.JSONDecodeError, AttributeError):
                                pass

                        logger.debug(f"[{AGENT_NAME}] Survey turn %d: %s(%s) → %d chars",
                                     turn + 1, fn_name,
                                     ", ".join(f"{k}={v!r}" for k, v in fn_args.items()),
                                     len(result_str))
                        messages.append({
                            "role": "tool",
                            "tool_call_id": tc["id"],
                            "content": result_str,
                        })

                    if survey_result:  # Loop broken by submit_work or repetition guard
                        break
                elif not content:
                    break
        finally:
            _survey_root_flag.reset(_root_token)

        if not survey_result:
            logger.warning(
                f"[{AGENT_NAME}] Survey exhausted %d turns without SURVEY_COMPLETE signal. "
                "Using last LLM response (%d chars) as fallback — design quality may be reduced.",
                PLANNING_SURVEY_MAX_TURNS, len(content),
            )
            survey_result = content or "Survey completed without explicit summary."

        logger.info(f"[{AGENT_NAME}] Codebase survey completed (%d chars)", len(survey_result))
        return survey_result

    # ------------------------------------------------------------------
    # Stage 4: Pitfall Detection
    # ------------------------------------------------------------------

    async def _stage_pitfall_detection(
        self, design: dict, survey: str
    ) -> list[dict]:
        """Deterministic checks + LLM edge case detection."""
        pitfalls: list[dict] = []

        # Deterministic: check dependency graph for cycles
        dep_graph = design.get("dependency_graph", {})
        if dep_graph:
            from app.agent.static_analysis import _detect_cycles
            cycles = _detect_cycles(dep_graph)
            if cycles:
                for cycle in cycles:
                    pitfalls.append({
                        "type": "circular_dependency",
                        "severity": "high",
                        "detail": f"Circular dependency: {' -> '.join(cycle)}",
                    })

        # Deterministic: file path safety
        from app.agent.tools import _assert_safe_path
        for entry in design.get("file_manifest", []):
            path = entry.get("path", "")
            if path:
                try:
                    # Pass path directly — _assert_safe_path uses set_task_git_cwd effective root.
                    _assert_safe_path(path)
                except ValueError as e:
                    pitfalls.append({
                        "type": "unsafe_path",
                        "severity": "critical",
                        "detail": str(e),
                    })

        # LLM: edge case detection
        _arch = self._arch_ctx
        if self._is_proof:
            _pitfall_system = self._stage_cfg.get("system_prompt_proof") or "You are a formal-proof quality reviewer. Use submit_work to output pitfalls."
            _pitfall_focus = (
                "Look for: missing helper lemmas, proof obligations without a clear tactic, "
                "`sorry` placeholders in the plan, import paths that don't exist in Mathlib, "
                "name clashes with existing Mathlib theorems, universe level mismatches, "
                "overly complex tactic chains that are likely to fail."
            )
        else:
            _pitfall_system = self._stage_cfg.get("system_prompt") or "You are a software quality analyst. Use submit_work to output pitfalls when ready."
            _pitfall_focus = (
                "Look for: edge cases, implicit dependencies, race conditions, "
                "state management issues, migration risks."
            )
        prompt = (
            (f"{_arch}\n\n" if _arch else "")
            + "Analyze this design for potential pitfalls:\n"
            f"{json.dumps(design, indent=1, ensure_ascii=True)}\n\n"
            f"{_pitfall_focus}\n"
            "To output pitfalls, call the submit_work tool with:\n"
            "payload={\"pitfalls\": [{\"type\": \"...\", \"severity\": \"low|medium|high|critical\", \"detail\": \"...\"}]}"
        )

        from app.agent.tools import build_tool_schemas, dispatch_tool
        pitfall_tools = build_tool_schemas(["submit_work"])

        try:
            response = await call_llm(
                [
                    {"role": "system", "content": _pitfall_system},
                    {"role": "user", "content": prompt},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                tools=pitfall_tools,
                tool_choice="auto",
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=AGENT_NAME,
            )
            self._track_tokens(response)
            
            assistant_msg = response.get("choices", [{}])[0].get("message", {})
            tool_calls = assistant_msg.get("tool_calls") or []
            
            data = None
            if tool_calls:
                for tc in tool_calls:
                    tc_result = dispatch_tool(
                        tc["function"]["name"],
                        json.loads(tc["function"]["arguments"]) if isinstance(tc["function"]["arguments"], str) else tc["function"]["arguments"],
                    )
                    if isinstance(tc_result, str) and "__maestro_terminal__" in tc_result:
                        data = json.loads(tc_result).get("payload")
                        break
            
            if data is None:
                # Fallback
                content = assistant_msg.get("content", "")
                data, _ = json.JSONDecoder().raw_decode(content.lstrip())
            
            pitfalls.extend(data.get("pitfalls", []))
        except Exception as e:
            logger.warning(f"[{AGENT_NAME}] Pitfall LLM check failed: %s", e)

        return pitfalls

    # ------------------------------------------------------------------
    # Stage 5: Plan Consolidation
    # ------------------------------------------------------------------

    async def _stage_consolidation(
        self, design: dict, pitfalls: list[dict], survey: str
    ) -> dict:
        """Merge the winning design with pitfall mitigations."""
        if not pitfalls:
            return design

        _arch = self._arch_ctx
        prompt = (
            (f"{_arch}\n\n" if _arch else "")
            + "You have a winning design and identified pitfalls. "
            "Produce a consolidated final design that incorporates mitigations "
            "for the identified pitfalls. Use the submit_work tool to output the result.\n\n"
            f"Original design:\n{json.dumps(design, indent=1, ensure_ascii=True)}\n\n"
            f"Pitfalls:\n{json.dumps(pitfalls, indent=1, ensure_ascii=True)}"
        )

        from app.agent.tools import build_tool_schemas, dispatch_tool
        consol_tools = build_tool_schemas(["submit_work"])

        _consol_system = (
            self._stage_cfg.get("system_prompt_proof") or "You are a formal proof specialist. Use submit_work to output the final proof design."
            if self._is_proof
            else self._stage_cfg.get("system_prompt") or "You are a software architect. Use submit_work to output the final design."
        )

        try:
            response = await call_llm(
                [
                    {"role": "system", "content": _consol_system},
                    {"role": "user", "content": prompt},
                ],
                base_url=self.llm_base_url,
                model=self.llm_model,
                tools=consol_tools,
                tool_choice="auto",
                task_id=self.task_id,
                llm_id=self.llm_id,
                budget_id=self.budget_id,
                agent_name=AGENT_NAME,
            )
            self._track_tokens(response)
            
            assistant_msg = response.get("choices", [{}])[0].get("message", {})
            tool_calls = assistant_msg.get("tool_calls") or []
            
            result = None
            if tool_calls:
                for tc in tool_calls:
                    tc_result = dispatch_tool(
                        tc["function"]["name"],
                        json.loads(tc["function"]["arguments"]) if isinstance(tc["function"]["arguments"], str) else tc["function"]["arguments"],
                    )
                    if isinstance(tc_result, str) and "__maestro_terminal__" in tc_result:
                        result = json.loads(tc_result).get("payload")
                        break
            
            if result is None:
                # Fallback
                content = assistant_msg.get("content", "")
                result, _ = json.JSONDecoder().raw_decode(content.lstrip())
            
            return result
        except Exception as e:
            logger.warning(f"[{AGENT_NAME}] Consolidation failed: %s. Using original design.", e)
            return design

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _track_tokens(self, response: dict) -> None:
        usage = response.get("usage", {})
        self._total_prompt += usage.get("prompt_tokens", 0)
        self._total_completion += usage.get("completion_tokens", 0)

    def _build_result(
        self, consolidated: dict, all_designs: list[dict],
        selected_index: int, review_votes: list[Vote],
        pitfalls: list[dict], survey: str,
        passed: bool = True,
    ) -> PlanningResult:
        # Parse file manifest
        file_manifest = []
        for entry in consolidated.get("file_manifest", []):
            file_manifest.append(FileManifestEntry(
                path=entry.get("path", ""),
                action=entry.get("action", "create"),
                purpose=entry.get("purpose", ""),
                estimated_lines=entry.get("estimated_lines", 0),
                depends_on=entry.get("depends_on", []),
            ))

        # Parse interface contracts
        contracts = []
        for c in consolidated.get("interface_contracts", []):
            contracts.append(InterfaceContract(
                component=c.get("component", ""),
                provides=c.get("provides", []),
                consumes=c.get("consumes", []),
                invariants=c.get("invariants", []),
            ))

        # Parse test strategy
        test_strategy = []
        for t in consolidated.get("test_strategy", []):
            test_strategy.append(TestStrategyEntry(
                component=t.get("component", ""),
                test_file=t.get("test_file", ""),
                test_cases=t.get("test_cases", []),
                fixtures=t.get("fixtures", []),
            ))

        # Parse implementation steps
        steps = []
        for s in consolidated.get("implementation_steps", []):
            steps.append(ImplementationStep(
                order=s.get("order", 0),
                component=s.get("component", ""),
                files=s.get("files", []),
                description=s.get("description", ""),
                depends_on=s.get("depends_on", []),
                estimated_context_tokens=s.get("estimated_context_tokens", 0),
            ))

        return PlanningResult(
            task_id=self.task_id,
            design_rationale=consolidated.get("design_rationale", ""),
            file_manifest=file_manifest,
            dependency_graph=consolidated.get("dependency_graph", {}),
            interface_contracts=contracts,
            test_strategy=test_strategy,
            implementation_steps=sorted(steps, key=lambda s: s.order),
            pitfalls_identified=pitfalls,
            review_votes=review_votes,
            best_of_n_designs=all_designs,
            selected_design_index=selected_index,
            confidence=80 if passed else 0,
            prompt_tokens=self._total_prompt,
            completion_tokens=self._total_completion,
        )

    def _store_result(self, result: PlanningResult) -> None:
        """Persist PlanningResult to the database.

        If ``self.run_row_id`` is set (i.e. the caller pre-created an
        ``in_progress`` row), update that row in-place so the row ID stays
        stable.  Otherwise fall back to creating a new row (scheduler path).
        """
        kwargs = dict(
            file_manifest=json.dumps([asdict(f) for f in result.file_manifest]),
            dependency_graph=json.dumps(result.dependency_graph),
            interface_contracts=json.dumps([asdict(c) for c in result.interface_contracts]),
            test_strategy=json.dumps([asdict(t) for t in result.test_strategy]),
            implementation_steps=json.dumps([asdict(s) for s in result.implementation_steps]),
            pitfalls_identified=json.dumps(result.pitfalls_identified),
            review_votes=json.dumps([
                {"stage": v.stage, "verdict": v.verdict.value, "confidence": v.confidence,
                 "justification": v.justification}
                for v in result.review_votes
            ]),
            best_of_n_designs=json.dumps(result.best_of_n_designs),
            selected_design_index=result.selected_design_index,
            confidence=result.confidence,
            prompt_tokens=result.prompt_tokens,
            completion_tokens=result.completion_tokens,
            status='active',
        )
        try:
            if self.run_row_id is not None:
                from app.database import update_planning_result
                from app.database.session import SessionLocal as _SL
                _db = _SL()
                try:
                    update_planning_result(_db, self.run_row_id, **kwargs)
                finally:
                    _db.close()
            else:
                from app.database import create_planning_result
                create_planning_result(task_id=result.task_id, **kwargs)
        except Exception as e:
            logger.error(f"[{AGENT_NAME}] Failed to store result: %s", e)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

async def run_planning_survey(
    task_id: str,
    task_title: str,
    task_description: str,
    *,
    llm_base_url: str | None = None,
    llm_model: str | None = None,
    llm_id: int | None = None,
    budget_id: int | None = None,
    max_context: int | None = None,
    project_path: str | None = None,
    project_name: str | None = None,
) -> dict:
    """Codebase survey + task classification for planning_survey_node.

    Returns dict: survey_summary, is_proof, is_simple, best_of_n.
    """
    if project_path is not None:
        from app.agent.tools import set_task_git_cwd
        set_task_git_cwd(project_path)
    pipeline = PlanningPipeline(
        task_id=task_id,
        task_title=task_title,
        task_description=task_description,
        all_tasks=[],
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_id=llm_id,
        budget_id=budget_id,
        max_context=max_context,
        project_name=project_name,
        project_root=project_path,
    )
    pipeline._is_proof = _is_proof_task(task_title, task_description)
    survey_summary = await pipeline._stage_codebase_survey()
    try:
        from app.database import get_task as _get_task_hist
        _t = _get_task_hist(task_id)
        if _t and _t.demotion_history:
            _recent = _t.demotion_history[-3:]
            _hist_block = "\n\n[PRIOR INDEV FAILURES — consider before designing]\n"
            for _d in _recent:
                _ts = _d.get("timestamp", "?")[:19]
                _reason = _d.get("reason", "?")
                _hist_block += f"  {_ts}: {_reason[:400]}\n"
            survey_summary += _hist_block
    except Exception:
        pass
    is_proof = pipeline._is_proof
    is_simple = (
        not is_proof
        and not _is_unit_test_task(task_title, task_description)
        and _is_simple_task(task_title, task_description, survey_summary)
    )
    best_of_n = 2 if is_simple else PLANNING_BEST_OF_N
    return {
        "survey_summary": survey_summary,
        "is_proof": is_proof,
        "is_simple": is_simple,
        "best_of_n": best_of_n,
    }


async def run_pitfall_detection(
    task_id: str,
    task_title: str,
    task_description: str,
    winning_design: dict,
    survey_summary: str,
    *,
    llm_base_url: str | None = None,
    llm_model: str | None = None,
    llm_id: int | None = None,
    budget_id: int | None = None,
    max_context: int | None = None,
    project_path: str | None = None,
    project_name: str | None = None,
    is_proof: bool = False,
) -> list:
    """Pitfall detection for planning_pitfalls node. Returns list of pitfall dicts."""
    if project_path is not None:
        from app.agent.tools import set_task_git_cwd
        set_task_git_cwd(project_path)
    pipeline = PlanningPipeline(
        task_id=task_id,
        task_title=task_title,
        task_description=task_description,
        all_tasks=[],
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_id=llm_id,
        budget_id=budget_id,
        max_context=max_context,
        project_name=project_name,
        project_root=project_path,
    )
    pipeline._is_proof = is_proof
    return await pipeline._stage_pitfall_detection(winning_design, survey_summary)


async def run_consolidation_and_store(
    task_id: str,
    task_title: str,
    task_description: str,
    winning_design: dict,
    pitfalls: list,
    survey_summary: str,
    all_tasks: list[dict],
    *,
    llm_base_url: str | None = None,
    llm_model: str | None = None,
    llm_id: int | None = None,
    budget_id: int | None = None,
    max_context: int | None = None,
    project_path: str | None = None,
    project_name: str | None = None,
    is_proof: bool = False,
) -> None:
    """Consolidate design + pitfall mitigations and store PlanningResult for planning_consolidate node."""
    if project_path is not None:
        from app.agent.tools import set_task_git_cwd
        set_task_git_cwd(project_path)
    pipeline = PlanningPipeline(
        task_id=task_id,
        task_title=task_title,
        task_description=task_description,
        all_tasks=all_tasks,
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_id=llm_id,
        budget_id=budget_id,
        max_context=max_context,
        project_name=project_name,
        project_root=project_path,
    )
    pipeline._is_proof = is_proof
    consolidated = await pipeline._stage_consolidation(winning_design, pitfalls, survey_summary)
    result = pipeline._build_result(
        consolidated=consolidated,
        all_designs=[winning_design],
        selected_index=0,
        review_votes=[],
        pitfalls=pitfalls,
        survey=survey_summary,
        passed=True,
    )
    result.survey_summary = survey_summary
    pipeline._store_result(result)

